spring.application.name=cinema_learn

server.port=8082

# Oracle Database Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=cinema123
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

# Schema configuration
spring.jpa.properties.hibernate.default_schema=CINEMA
spring.jpa.properties.hibernate.dialect.oracle.use_quoted_identifiers=false

